//! ObjectIO Protocol - gRPC service definitions
//!
//! This crate contains the protobuf-generated code for ObjectIO's
//! internal gRPC services.

// Everything below is generated by tonic/prost from proto/*.proto at build
// time. The workspace turns on clippy's pedantic and nursery groups, which
// then fire in their hundreds on code no one here writes or can change —
// `result_large_err` alone accounts for 198. Linting generated output only
// teaches people to ignore the linter.
#![allow(
    clippy::result_large_err,
    clippy::large_enum_variant,
    clippy::doc_markdown,
    clippy::must_use_candidate,
    clippy::missing_errors_doc,
    clippy::derive_partial_eq_without_eq,
    clippy::wildcard_imports,
    clippy::pedantic,
    clippy::nursery
)]

/// Storage service (OSD operations)
pub mod storage {
    tonic::include_proto!("objectio.storage");
}

/// Metadata service (bucket and object operations)
pub mod metadata {
    tonic::include_proto!("objectio.metadata");
}

/// Cluster service (node and disk management)
pub mod cluster {
    tonic::include_proto!("objectio.cluster");
}

/// Block service (volume and snapshot management)
pub mod block {
    tonic::include_proto!("objectio.block");
}

/// Raft consensus transport (meta ↔ meta, openraft 0.9).
/// `RaftEnvelope` carries a JSON-encoded openraft request/response as an
/// opaque byte payload so proto schema changes aren't needed when
/// openraft's struct shapes evolve.
pub mod raft {
    tonic::include_proto!("objectio.raft");
}
