//! ObjectIO Protocol - gRPC service definitions
//!
//! This crate contains the protobuf-generated code for ObjectIO's
//! internal gRPC services.

// Everything below is generated by tonic/prost from proto/*.proto at build
// time. The workspace turns on clippy's pedantic and nursery groups, which
// then fire in their hundreds on code no one here writes or can change —
// `result_large_err` alone accounts for 198. Linting generated output only
// teaches people to ignore the linter.
#![allow(
    clippy::result_large_err,
    clippy::large_enum_variant,
    clippy::doc_markdown,
    clippy::must_use_candidate,
    clippy::missing_errors_doc,
    clippy::derive_partial_eq_without_eq,
    clippy::wildcard_imports,
    clippy::pedantic,
    clippy::nursery
)]

/// Storage service (OSD operations)
pub mod storage {
    tonic::include_proto!("objectio.storage");
}

/// Metadata service (bucket and object operations)
pub mod metadata {
    tonic::include_proto!("objectio.metadata");
}

impl metadata::ObjectMeta {
    /// Where this copy stands in the order of writes to its key
    /// (objectio-docs core/object-metadata-quorum.md): by object (its stamp,
    /// then its id), then, between copies of one object, by update. A copy
    /// with a higher order holds the newer write.
    #[must_use]
    pub fn write_order(&self) -> (u64, &[u8], u64) {
        (self.stamp, self.object_id.as_slice(), self.update_stamp)
    }
}

/// The gRPC metadata an OSD sets on a request it refuses as placed under
/// an older epoch than it knows for the placement group (B31): the epoch
/// it knows. The gateway takes it as "place again".
pub const STALE_EPOCH_HEADER: &str = "x-objectio-pg-epoch";

/// Cluster service (node and disk management)
pub mod cluster {
    tonic::include_proto!("objectio.cluster");
}

/// Block service (volume and snapshot management)
pub mod block {
    tonic::include_proto!("objectio.block");
}

/// Raft consensus transport (meta ↔ meta, openraft 0.9).
/// `RaftEnvelope` carries a JSON-encoded openraft request/response as an
/// opaque byte payload so proto schema changes aren't needed when
/// openraft's struct shapes evolve.
pub mod raft {
    tonic::include_proto!("objectio.raft");
}

/// HTTP/2 settings for servers that receive shards. Hand-written, so it
/// keeps the workspace lints the generated modules opt out of.
#[warn(clippy::pedantic, clippy::nursery)]
pub mod rpc_metrics;
pub mod transport;

/// Deduplication policy resolution, shared by meta and the gateway.
#[warn(clippy::pedantic, clippy::nursery)]
pub mod dedup;
